baseurl = "https://jasminykhan.github.io/"
languageCode = "en-us"
title = "Bring Osman Home"
theme = "hugo-theme-anubis"
enableInlineShortcodes = true

# `hugo new` automatically opened text editor
newContentEditor = ""

# i18n
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

# Pluralize titles in lists?
pluralizeListTitles = false

# The length of text in words to show in summary
summaryLength = 42

# Enable Emoji emoticons support?
enableEmoji = false

# Text to display for footnote return links
footnoteReturnLinkContents = "↩"

# Enable `.GitInfo` object for each page?
enableGitInfo = false

# Enable generation of `robots.txt` file?
enableRobotsTXT = true

# Number of items per page in paginated
# lists (valid for the `posts` homepage
# layout in MemE)
paginate = 5

# URL related
disablePathToLower = false
relativeURLs = false
uglyURLs = false

# URL structure
[permalinks]
    categories = "/categories/:slug/"
    tags = "/tags/:slug/"

# Taxonomies
[taxonomies]
    category = "categories"
    tag = "tags"

# Modified date
[frontmatter]
    lastmod = ["lastmod", ":git", ":fileModTime", ":default"]

# Markdown renderer
[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark]
        [markup.goldmark.extensions]
            definitionList = true
            footnote = true
            linkify = true
            strikethrough = true
            table = true
            taskList = true
            typographer = true
        [markup.goldmark.parser]
            attribute = true
            autoHeadingID = true
            autoHeadingIDType = "github"
        [markup.goldmark.renderer]
            hardWraps = false
            unsafe = true
            xHTML = false
    [markup.highlight]
        codeFences = true
        guessSyntax = false
        lineNos = true
        lineNumbersInTable = true
        noClasses = false
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 6
        ordered = true

# HTML minify
[minify.tdewolff.html]
    keepWhitespace = false

# Author’s information
[author]
    # Name
    name = "Save Osman"
    # Email
    email = "jasminykhan@gmail.com"
    # Motto or introduction
    motto = "Viva La Vida"
    # Avatar
    # avatar = "/icons/apple-touch-icon.png"

# Related content
[related]
    threshold = 80
    includeNewer = true
    toLower = true
    [[related.indices]]
        name = "categories"
        weight = 100
    [[related.indices]]
        name = "tags"
        weight = 95
    [[related.indices]]
        name = "date"
        weight = 10
        pattern = "2006"

# MIME type of Atom
[mediaTypes."application/atom+xml"]
    suffixes = ["xml"]

# Custom Atom template of MemE
[outputFormats.SectionsAtom]
    mediaType = "application/atom+xml"
    baseName = "atom"

# Custom RSS template of MemE
[outputFormats.SectionsRSS]
    mediaType = "application/rss+xml"
    baseName = "rss"

# Search index for lunr.js
[outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "search"

# Search index for Algolia
[outputFormats.Algolia]
    mediaType = "application/json"
    baseName = "algolia"
    isPlainText = true
    notAlternative = true

# Hugo’s output control
[outputs]
    page = ["HTML"]
    # home = ["HTML", "SectionsAtom", "SectionsRSS", "SearchIndex", "Algolia"]
    home = ["HTML", "SectionsAtom", "SectionsRSS", "SearchIndex"]
    section = ["HTML"]
    taxonomy = ["HTML"]
    term = ["HTML"]

# Maximum number of items in the Atom & RSS feed
[services.rss]
    limit = -1



##########################################
# Menu Settings

# MemE supports the following four menus:
# 1. main       Menu bar below the header
#               (center layout) or inside
#               the header (flex layout)
# 2. home       Links at the bottom of the
#               homepage (valid for the
#               `poetry` and `footage`
#               homepage layout)
# 3. socials    Social bar (minimal footer
#               in about page)
# 4. links      Link bar (minimal footer
#               in about page)

# The configuration instructions in the
# menu are as follows:
# pageref/url   internal/external URL
# name          Text (won’t display if it
#               is left empty("") or does
#               not exist)
# weight        Position
# pre           Type of link (internal or
#               external)
# post          Icon (won’t display if it
#               is left empty("") or does
#               not exist)
# identifier    Icon’s class name
#               (there are three special
#               values for header layout
#               flex: `theme-switcher`,
#               `lang-switcher`, `search`)

[menu]
    ## Menu bar
    [[menu.main]]
        pageref = "/"
        name = "Home"
        weight = 1
        pre = "internal"
        post = "home"
    [[menu.main]]
        pageref = "/contact"
        name = "Contact"
        weight = 2
        pre = "internal"
        post = "contact"


##########################################
# Theme Settings

[params]
    ######################################
    # Header

    enableHeader = true

    enableHeaderAutoHide = false
    # Note: works for header layout flex only

    displayHeaderInHome = true
    # Note: invalid for header layout flex

    headerBackground = "linear-gradient(90deg, #f795331a 0, #f370551a 15%, #ef4e7b1a 30%, #a166ab1a 44%, #5073b81a 58%, #1098ad1a 72%, #07b39b1a 86%, #6dba821a 100%)"
    # Note: https://developer.mozilla.org/en-US/docs/Web/CSS/background

    headerLayout = "flex"
    # Note: center or flex

    # Hide menu bar and display a toggle
    # on narrow screen?
    enableNavToggle = true

    navHeight = "10em"
    # Note: menu bar height when it’s
    #       toggled


    ######################################
    # Brand Bar (inside header)

    # Use SVG?
    siteBrandSVG = false
    # If true, put your SVG in the `SVG.toml`
    # file and configure the following options.
    # Unit: px
    siteBrandSVGWidth = 250
    siteBrandSVGHeight = 100
    siteBrandSVGFill = "#fff"
    # If false, your site title will be
    # used as the default and displayed as
    # text. The font size and font color
    # can be configured below. The font
    # family can be configured in typography
    # section at the bottom of this file.
    # Unit: em
    siteBrandFontSize = 1
    siteBrandFontColor = "var(--color-contrast-high)"


    ######################################
    # Menu Bar

    enableMenu = true
    # Note: invalid for header layout flex

    displayMenuInHome = true
    # Note: invalid for header layout flex

    # Highlight current menu item by section?
    activeInSection = false
    # Note: if true, the menu item in the
    #       post page will be highlighted
    #       also if that post’s section is
    #       the `url` of that menu item


    ######################################
    # Homepage Layout

    # For homepage layout, MemE has the
    # following four different types:
    # 1. poetry    A few lines of verse
    # 2. footage   With fullscreen background videos
    # 3. posts     List of post’s summary
    # 4. page      Normal page/post

    homeLayout = "posts"

    ## Poetry
    # Verse (Markdown supported)
    homePoetry = []
    # Padding of links at the bottom
    # Unit: em
    homeLinksPadding = 1

    ## Footage
    homePoster = ""
    homeVideoWebm = ""
    homeVideoMp4 = ""
    homeLogo = ""
    homeLogoLink = ""
    homeTitle = ""
    homeMotto = ""
    homeDescription = ""
    homeKeywords = ""
    homeLinksDelimiter = ""


    ######################################
    # Site Info

    siteLogo = "/icons/apple-touch-icon.png"
    # Note: used for JSON-LD, Open Graph

    siteDescription = "This website serves to bring attention and inform the public of the brutal conditions Osman and other americans have suffered at the hands of the Maduro regime."
    
    style = "light"

    hideThemeToggle = false
    hideThemeToggleInHome = false